const allTasks = [
    // PACK 1
    // CURRENTLY AI TRANSLATED, NEED TO BE CHECKED
    {points: 1, pack: 1, taskId: 1, 
        description: "En algún juego durante la velada, queda en primer y último lugar a la vez."},
    {points: 1, pack: 1, taskId: 2, 
        description: "Sabotea un juego en equipo. Si tu equipo pierde y nadie sospecha de ti, puedes revelárselo a tu compañero y dejar que marque una de sus misiones como completada."},
    {points: 1, pack: 1, taskId: 3, 
        description: "Propón jugar a un juego que ninguno de los participantes haya jugado antes, y pierde."},
    {points: 1, pack: 1, taskId: 4, 
        description: "Propón jugar a un juego conocido pero con reglas modificadas. Gana."},
    {points: 1, pack: 1, taskId: 5, 
        description: "Convence a los demás jugadores de jugar a algo, pero no participes tú."},
    {points: 1, pack: 1, taskId: 6, 
        description: "Intercambia algunos muebles, objetos de decoración u otros elementos grandes, haz una foto y vuelve a dejarlos en su sitio."},
    {points: 1, pack: 1, taskId: 7, 
        description: "Sustituye o crea un elemento decorativo con un dibujo o una foto de uno de los jugadores. Debe pasar desapercibido al menos una hora."},
    {points: 1, pack: 1, taskId: 8, 
        description: "Esconde una nota con el nombre de un jugador en un libro. Haz que la encuentre por casualidad."},
    {points: 1, pack: 1, taskId: 9, 
        description: "Cambia objetos entre distintas zonas del piso (por ejemplo, algo de la cocina al baño y viceversa). El cambio debe pasar desapercibido durante una hora."},
    {points: 1, pack: 1, taskId: 10, 
        description: "Añade un aroma agradable (obligatorio) a la habitación. Alguien tiene que notarlo."},
    {points: 1, pack: 1, taskId: 11, 
        description: "Actúa de forma sospechosa. Si alguien te pilla, debe descartar una de sus misiones activas si tiene alguna."},
    {points: 1, pack: 1, taskId: 12, 
        description: "Completa la misión de otro jugador antes que él."},
    {points: 1, pack: 1, taskId: 13, 
        description: "Averigua qué misión tiene otro jugador y que te pillen intentando hacerla. Si fallas al adivinar, pierdes esta misión."},
    {points: 1, pack: 1, taskId: 14, 
        description: "Convence a otro jugador de completar una de tus otras misiones. Si lo consigue, puede marcar una de las suyas como completada, pero tú no puedes marcar la tuya."},
    {points: 1, pack: 1, taskId: 15, 
        description: "Ayuda a otro jugador con su misión."},
    {points: 1, pack: 1, taskId: 16, 
        description: "Embauca a otro jugador haciéndole creer que le ayudas con su misión."},
    {points: 1, pack: 1, taskId: 17, 
        description: "Usa la misma frase al menos 4 veces durante la velada."},
    {points: 1, pack: 1, taskId: 18, 
        description: "Habla usando solo dos palabras de tu elección durante 15 minutos."},
    {points: 1, pack: 1, taskId: 19, 
        description: "Inventa un gesto único y úsalo en conversación con 3 jugadores distintos o 3 veces con el mismo jugador."},
    {points: 1, pack: 1, taskId: 20, 
        description: "Imita la postura de otro jugador durante 2 minutos. La postura debe ser reconocible."},
    {points: 1, pack: 1, taskId: 21, 
        description: "Mantén un diálogo en el que permanezcas en silencio al menos un minuto."},
    {points: 1, pack: 1, taskId: 22, 
        description: "Incorpora con naturalidad 3 citas de la película favorita de uno de los jugadores en una conversación."},
    {points: 1, pack: 1, taskId: 23, 
        description: "Elige un animal. Usa 5 juegos de palabras relacionados con ese animal en una conversación."},
    {points: 1, pack: 1, taskId: 24, 
        description: "Menciona con naturalidad los títulos de 5 películas o series distintas en una conversación que no trate de cine o televisión."},
    {points: 1, pack: 1, taskId: 25, 
        description: "Menciona con naturalidad el nombre de 5 bandas distintas en una conversación que no trate de música."},
    {points: 1, pack: 1, taskId: 26, 
        description: "Cuéntale un chiste a alguien. Nadie debe reírse."},
    {points: 1, pack: 1, taskId: 27, 
        description: "Haz que otro jugador imite a una celebridad que otro jugador no soporta."},
    {points: 1, pack: 1, taskId: 28, 
        description: "Susúrrale a otro jugador. Debe empezar a susurrar también. Asegúrate de que nadie os escuche."},
    {points: 1, pack: 1, taskId: 29, 
        description: "Consigue que tres personas cambien de sitio durante su conversación sin que sepan por qué."},
    {points: 1, pack: 1, taskId: 30, 
        description: "Añade a tu outfit una prenda similar a la de otro jugador. Tiene que ser ese jugador quien se dé cuenta."},
    {points: 1, pack: 1, taskId: 31, 
        description: "Cambia una prenda grande o tres pequeñas. Nadie debe notar el cambio durante una hora."},
    {points: 1, pack: 1, taskId: 32, 
        description: "Pide a otro jugador que intercambie contigo alguna prenda. Si nadie lo nota en una hora, puede marcar una de sus misiones como completada."},
    {points: 1, pack: 1, taskId: 33, 
        description: "Aprende un truco de magia y hazlo, o convence a otro jugador de que haga uno."},
    {points: 1, pack: 1, taskId: 34, 
        description: "Otro jugador debe perder un lápiz o un bolígrafo y luego encontrarlo."},
    {points: 1, pack: 1, taskId: 35, 
        description: "Otro jugador debe encontrar una carta (o algo parecido) en uno de sus bolsillos."},
    {points: 1, pack: 1, taskId: 36, 
        description: "Otro jugador debe encontrar una carta (o algo parecido) entre sus pertenencias."},
    {points: 1, pack: 1, taskId: 37, 
        description: "Escribe una predicción sobre lo que hará o dirá otro jugador. Muéstrasela cuando se cumpla."},
    {points: 1, pack: 1, taskId: 38, 
        description: "Esconde un objeto de la mesa de modo que nadie note su ausencia durante una hora."},
    {points: 1, pack: 1, taskId: 39, 
        description: "Haz que alguien tararee el tema de su serie favorita."},
    {points: 1, pack: 1, taskId: 40, 
        description: "Empieza a cantar algo pegadizo para que otro jugador se una."},
    {points: 1, pack: 1, taskId: 41, 
        description: "Canta una canción mal a propósito para que alguien te corrija. O corrige a alguien que cante mal."},
    {points: 1, pack: 1, taskId: 42, 
        description: "Haz que alguien adivine lo que tarareas, o adivina lo que tararea otro jugador."},
    {points: 1, pack: 1, taskId: 43, 
        description: "Convence a otro jugador de añadir a su playlist una canción que tú elijas."},
    {points: 1, pack: 1, taskId: 44, 
        description: "Crea una «marca negra»: escribe el nombre de un jugador y dibuja algo inquietante en un papel. Ese jugador debe encontrarla. Si la encuentra otro jugador, pierdes."},
    {points: 1, pack: 1, taskId: 45, 
        description: "Esconde 5 objetos pequeños (tesoros) en la habitación. Dibuja un mapa del tesoro y dáselo a otro jugador. Si encuentra todo, ganas y puede marcar una de sus misiones como completada. Si encuentra el tesoro otra persona, puede marcar una de las suyas y los dos perdéis."},
    {points: 1, pack: 1, taskId: 46, 
        description: "Haz una foto de otro jugador como si fuera a través de un catalejo."},
    {points: 1, pack: 1, taskId: 47, 
        description: "Otro jugador debe participar contigo en un duelo imaginario."},
    {points: 1, pack: 1, taskId: 48, 
        description: "Alguien debe dirigirse a ti como Capitán."},
    {points: 1, pack: 1, taskId: 49, 
        description: "Averigua qué cóctel nunca ha probado otro jugador y convéncelo de probarlo. Debe ser seguro y agradable para él."},
    {points: 1, pack: 1, taskId: 50, 
        description: "Prueba las bebidas de otros jugadores con su permiso 4 veces."},
    {points: 1, pack: 1, taskId: 51, 
        description: "Convence a alguien de añadir un ingrediente sencillo a su bebida, como zumo de limón o un jarabe."},
    {points: 1, pack: 1, taskId: 52, 
        description: "En algún momento, otro jugador debe empezar a bailar con la bebida en la mano."},
    {points: 1, pack: 1, taskId: 53, 
        description: "Tu bebida debe ser probada 4 veces. Debe ser segura y agradable de probar."},
    {points: 1, pack: 1, taskId: 54, 
        description: "Haz una foto de alguien dibujando algo."},
    {points: 1, pack: 1, taskId: 55, 
        description: "Haz una foto de alguien cantando algo."},
    {points: 1, pack: 1, taskId: 56, 
        description: "Haz una foto de otros jugadores (al menos tres o todos) a través de un objeto reflectante."},
    {points: 1, pack: 1, taskId: 57, 
        description: "Haz que tu selfie aparezca en el móvil de tres jugadores o de todos."},
    {points: 1, pack: 1, taskId: 58, 
        description: "Recrea una obra de arte con objetos que tengas a mano y haz una foto."},
    {points: 1, pack: 1, taskId: 59, 
        description: "Haz una foto de otro jugador que recuerde a una obra de arte famosa."},
    {points: 1, pack: 1, taskId: 60, 
        description: "Haz una foto de la lista de misiones de otro jugador."},
    {points: 1, pack: 1, taskId: 61, 
        description: "Quédate en una habitación a oscuras durante 2 minutos. No puede ser el baño ni el aseo."},
    {points: 1, pack: 1, taskId: 62, 
        description: "Escóndete en una habitación con otras personas. No deben encontrarte durante al menos un minuto."},
    {points: 1, pack: 1, taskId: 63, 
        description: "Elige un jugador y escóndete de él en 30 segundos. Si te encuentra en 2 minutos, puede marcar una de sus misiones como completada. Si te encuentran, pierdes. Los demás jugadores no pueden pillarte en esta misión."},
    {points: 1, pack: 1, taskId: 64, 
        description: "Elige un jugador y proponle que se esconda 30 segundos. Si no lo encuentras en 2 minutos, pierdes. Si ganas, el otro puede marcar una de sus misiones como completada. Los demás jugadores no pueden pillarte en esta misión."},
    {points: 1, pack: 1, taskId: 65, 
        description: "Propón un juego a otro jugador: escondes una de sus cosas en la habitación en 20 segundos. Si la encuentra en 5 minutos, pierdes y puede marcar una de sus misiones como completada."},
    {points: 1, pack: 1, taskId: 66, 
        description: "Dibuja el nombre de otro jugador en tu cuerpo. Ese jugador tiene que darse cuenta."},
    {points: 1, pack: 1, taskId: 67, 
        description: "Dibuja algo en otro jugador que no se dé cuenta hasta al menos 15 minutos después. Asegúrate de tener suficiente confianza con esa persona para esta misión."},
    {points: 1, pack: 1, taskId: 68, 
        description: "Convence a otro jugador de que dibuje o escriba algo en ti."},
    {points: 1, pack: 1, taskId: 69, 
        description: "Dale a otro jugador un objeto raro que deba guardar al menos una hora."},
    {points: 1, pack: 1, taskId: 70, 
        description: "Dale un objeto a otro jugador y vete. Haz que te encuentre y te lo devuelva."},
    {points: 1, pack: 1, taskId: 71, 
        description: "Un jugador elegido debe dibujar al menos dos dibujos distintos."},
    {points: 1, pack: 1, taskId: 72, 
        description: "Otro jugador debe dibujar un mapa o un dibujo que indique dónde está algún objeto."},
    {points: 1, pack: 1, taskId: 73, 
        description: "Pide a otro jugador que te prepare un plato sin un ingrediente imprescindible para ese plato, sin nombrar ese ingrediente ni su tipo."}
];

module.exports = allTasks;
