const allTasks = [
    // PACK 1
    {points: 1, pack: 1, taskId: 1, 
        description: "In some game during the evening, finish in both first and last place."},
    {points: 1, pack: 1, taskId: 2, 
        description: "Sabotage a team game. If your team loses and no one suspects you of sabotage, you can reveal it to your partner and let them mark one of their tasks as completed."},
    {points: 1, pack: 1, taskId: 3, 
        description: "Suggest playing a game that none of the participants have played before, and lose."},
    {points: 1, pack: 1, taskId: 4, 
        description: "Suggest playing a familiar game but with modified rules. Win."},
    {points: 1, pack: 1, taskId: 5, 
        description: "Convince the other players to play a game but don’t participate yourself."},
    {points: 1, pack: 1, taskId: 6, 
        description: "Swap a few pieces of furniture/decor/other large items, take a photo, and then return them to their original positions."},
    {points: 1, pack: 1, taskId: 7, 
        description: "Replace or create a decor element with a drawing or photo of one of the players. It must remain unnoticed for at least an hour."},
    {points: 1, pack: 1, taskId: 8, 
        description: "Hide a note with a player's name in a book. Make sure they find it accidentally."},
    {points: 1, pack: 1, taskId: 9, 
        description: "Switch items between different areas of the apartment (for example, something from the kitchen to the bathroom and vice versa). The switch should go unnoticed for an hour."},
    {points: 1, pack: 1, taskId: 10, 
        description: "Add a pleasant (mandatory) scent to the room. Someone must notice it."},
    {points: 1, pack: 1, taskId: 11, 
        description: "Act suspiciously. If someone catches you, they must discard one of their active tasks if they have one."},
    {points: 1, pack: 1, taskId: 12, 
        description: "Complete another player’s task before they do."},
    {points: 1, pack: 1, taskId: 13, 
        description: "Figure out what task another player has and get caught trying to do it. If you guess wrong, you fail this task."},
    {points: 1, pack: 1, taskId: 14, 
        description: "Convince another player to complete one of your other tasks. If they succeed, they can mark one of their tasks as completed, but you cannot mark yours."},
    {points: 1, pack: 1, taskId: 15, 
        description: "Help another player with their task."},
    {points: 1, pack: 1, taskId: 16, 
        description: "Set up another player by pretending to help them with their task."},
    {points: 1, pack: 1, taskId: 17, 
        description: "Use the same phrase at least 4 times during the evening."},
    {points: 1, pack: 1, taskId: 18, 
        description: "Speak using only two words of your choice for 15 minutes."},
    {points: 1, pack: 1, taskId: 19, 
        description: "Invent a unique gesture and use it in conversation with 3 different players or 3 times with the same player."},
    {points: 1, pack: 1, taskId: 20, 
        description: "Mimic another player's posture for 2 minutes. The posture should be distinctive."},
    {points: 1, pack: 1, taskId: 21, 
        description: "Engage in a dialogue where you stay silent for at least a minute."},
    {points: 1, pack: 1, taskId: 22, 
        description: "Casually incorporate 3 quotes from a favorite movie of one of the players into your conversation."},
    {points: 1, pack: 1, taskId: 23, 
        description: "Pick an animal. Use 5 puns related to that animal in conversation."},
    {points: 1, pack: 1, taskId: 24, 
        description: "Casually mention the titles of 5 different movies or TV series in a conversation that isn’t about film or TV."},
    {points: 1, pack: 1, taskId: 25, 
        description: "Casually mention the names of 5 different musical bands in a conversation that isn’t about music."},
    {points: 1, pack: 1, taskId: 26, 
        description: "Tell someone a joke. No one should laugh."},
    {points: 1, pack: 1, taskId: 27, 
        description: "Make another player imitate a celebrity disliked by another player."},
    {points: 1, pack: 1, taskId: 28, 
        description: "Whisper to another player. They should start whispering too. Make sure no one eavesdrops on you."},
    {points: 1, pack: 1, taskId: 29, 
        description: "Get three people to switch places during their conversation without them realizing why."},
    {points: 1, pack: 1, taskId: 30, 
        description: "Add an item of clothing similar to another player's to your outfit. The player must be the one to notice."},
    {points: 1, pack: 1, taskId: 31, 
        description: "Change one large or three small clothing items. No one should notice the change for an hour."},
    {points: 1, pack: 1, taskId: 32, 
        description: "Ask another player to swap clothing items with you. If no one notices for an hour, they can mark one of their tasks as completed."},
    {points: 1, pack: 1, taskId: 33, 
        description: "Learn a magic trick and perform it, or convince another player to perform one."},
    {points: 1, pack: 1, taskId: 34, 
        description: "Another player should lose a pencil or pen and then find it."},
    {points: 1, pack: 1, taskId: 35, 
        description: "Another player should find a card (or something similar) in one of their pockets."},
    {points: 1, pack: 1, taskId: 36, 
        description: "Another player should find a card (or something similar) among their belongings."},
    {points: 1, pack: 1, taskId: 37, 
        description: "Write a prediction about what another player will do or say. Show them the prediction once it happens."},
    {points: 1, pack: 1, taskId: 38, 
        description: "Hide an item from the table so that no one notices its absence for an hour."},
    {points: 1, pack: 1, taskId: 39, 
        description: "Get someone to hum the theme from their favorite TV show."},
    {points: 1, pack: 1, taskId: 40, 
        description: "Start singing something catchy so that another player joins in."},
    {points: 1, pack: 1, taskId: 41, 
        description: "Sing a song incorrectly so that someone corrects you. Alternatively, correct someone else's incorrect singing."},
    {points: 1, pack: 1, taskId: 42, 
        description: "Have someone guess what you're humming, or guess what another player is humming."},
    {points: 1, pack: 1, taskId: 43, 
        description: "Convince another player to add a song of your choice to their playlist."},
    {points: 1, pack: 1, taskId: 44, 
        description: "Create a 'black mark': write a player’s name and draw a spooky image on a piece of paper. This player must find the black mark. If another player finds it, you fail."},
    {points: 1, pack: 1, taskId: 45, 
        description: "Hide 5 small objects (treasures) in the room. Draw a treasure map and give it to another player. If they find everything, you win and they can mark one of their tasks as completed. If someone else finds the treasure, they can mark one of their tasks as completed, and you both lose."},
    {points: 1, pack: 1, taskId: 46, 
        description: "Take a photo of another player as if through a spyglass."},
    {points: 1, pack: 1, taskId: 47, 
        description: "Another player must participate with you in an imaginary duel."},
    {points: 1, pack: 1, taskId: 48, 
        description: "Someone must address you as Captain."},
    {points: 1, pack: 1, taskId: 49, 
        description: "Find out what cocktail another player has never tried and convince them to try it. This cocktail should not harm the player and should be enjoyable for them."},
    {points: 1, pack: 1, taskId: 50, 
        description: "Try the drinks of other players with their permission 4 times."},
    {points: 1, pack: 1, taskId: 51, 
        description: "Convince someone to add a simple ingredient to their drink, like lemon juice or syrup."},
    {points: 1, pack: 1, taskId: 52, 
        description: "At some point, another player must start dancing with a drink in hand."},
    {points: 1, pack: 1, taskId: 53, 
        description: "Your drink must be tasted 4 times. The drink should be safe and pleasant to taste."},
    {points: 1, pack: 1, taskId: 54, 
        description: "Take a photo of someone drawing something."},
    {points: 1, pack: 1, taskId: 55, 
        description: "Take a photo of someone singing something."},
    {points: 1, pack: 1, taskId: 56, 
        description: "Take a photo of other players (at least three or all) through a reflective object."},
    {points: 1, pack: 1, taskId: 57, 
        description: "Make your selfie appear on the phones of three or all players."},
    {points: 1, pack: 1, taskId: 58, 
        description: "Recreate a piece of art using available items and take a photo."},
    {points: 1, pack: 1, taskId: 59, 
        description: "Take a photo of another player that resembles a famous work of art."},
    {points: 1, pack: 1, taskId: 60, 
        description: "Take a photo of someone else's task list."},
    {points: 1, pack: 1, taskId: 61, 
        description: "Sit in a room with the lights off for 2 minutes. This cannot be a bathroom or toilet."},
    {points: 1, pack: 1, taskId: 62, 
        description: "Hide in a room with other people. Do not be discovered for at least a minute."},
    {points: 1, pack: 1, taskId: 63, 
        description: "Choose a player and hide from them within 30 seconds. If they find you within 2 minutes, they can mark one of their tasks as completed. If you are found, you lose. Other players cannot catch you for this task."},
    {points: 1, pack: 1, taskId: 64, 
        description: "Choose a player and suggest they hide for 30 seconds. If you cannot find them within 2 minutes, you lose. If you win, the other player can mark one of their tasks as completed. Other players cannot catch you for this task."},
    {points: 1, pack: 1, taskId: 65, 
        description: "Propose a game to another player: you hide one of their belongings in the room within 20 seconds. If they can find it within 5 minutes, you lose, and they can mark one of their tasks as completed."},
    {points: 1, pack: 1, taskId: 66, 
        description: "Draw the name of another player on your body. This player must notice it."},
    {points: 1, pack: 1, taskId: 67, 
        description: "Draw a picture on another player that they will notice at least 15 minutes later. Make sure you are close enough with this player for such a task."},
    {points: 1, pack: 1, taskId: 68, 
        description: "Convince another player to draw or write something on you."},
    {points: 1, pack: 1, taskId: 69, 
        description: "Give another player an unusual item that they must keep for at least an hour."},
    {points: 1, pack: 1, taskId: 70, 
        description: "Give another player an item and leave. Make it so that this player finds you and returns this item to you."},
    {points: 1, pack: 1, taskId: 71, 
        description: "Another chosen player must draw at least two different pictures."},
    {points: 1, pack: 1, taskId: 72, 
        description: "Another player must draw a map or a picture indicating the location of some object or item."},
    {points: 1, pack: 1, taskId: 73, 
        description: "Ask another player to make you a dish without a certain ingredient that is impossible to imagine that dish without, without naming that ingredient or type of ingredient."}
];

module.exports = allTasks;