const allTasks = [
    // PACK 1
    {points: 1, pack: 1, taskId: 1, 
        description: "Nehme in einem Spiel an einem Abend den ersten und den letzten Platz ein."},
    {points: 1, pack: 1, taskId: 2, 
        description: "Sabotiere ein Teamspiel. Wenn ihr verliert und niemand dich des Sabotage beschuldigt, kannst du deinem Partner erzählen und ihm die Möglichkeit geben, eine Aufgabe abzuschließen."},
    {points: 1, pack: 1, taskId: 3, 
        description: "Schlage vor, ein Spiel zu spielen, das niemand der Beteiligten vorher gespielt hat, und verliere."},
    {points: 1, pack: 1, taskId: 4, 
        description: "Schlage vor, ein vertrautes Spiel zu spielen, aber mit modifizierten Regeln. Gewinne."},
    {points: 1, pack: 1, taskId: 5, 
        description: "Überzeuge andere Spieler, ein Spiel zu spielen, nimm aber nicht daran teil."},
    {points: 1, pack: 1, taskId: 6, 
        description: "Verschiebe einige Möbelstücke/Dekorationsgegenstände/andere große Gegenstände, mache ein Foto und bringe sie zurück an ihren Platz."},
    {points: 1, pack: 1, taskId: 7, 
        description: "Ersetze/gestalte ein Dekorationselement mit einer Zeichnung/Fotografie eines der Spieler. Mindestens eine Stunde sollte dieses Element unbemerkt stehen."},
    {points: 1, pack: 1, taskId: 8, 
        description: "Verstecke einen Zettel mit dem Namen eines Spielers in einem Buch. Lass ihn zufällig diesen Zettel finden."},
    {points: 1, pack: 1, taskId: 9, 
        description: "Tausche Gegenstände aus verschiedenen Bereichen der Wohnung (z. B. etwas aus der Küche ins Bad und umgekehrt). Der Tausch darf innerhalb einer Stunde nicht bemerkt werden."},
    {points: 1, pack: 1, taskId: 10, 
        description: "Füge dem Raum einen angenehmen (unbedingt) Duft hinzu. Jemand aus den Spielern sollte dies bemerken."},
    {points: 1, pack: 1, taskId: 11, 
        description: "Verhalte dich verdächtig. Wenn dich jemand dabei erwischt, muss der Spieler, der dich erwischt hat, eine seiner aktiven Aufgaben abgeben, falls er eine hat."},
    {points: 1, pack: 1, taskId: 12, 
        description: "Erfülle die Aufgabe eines anderen Spielers vor ihm."},
    {points: 1, pack: 1, taskId: 13, 
        description: "Finde heraus, welche Aufgabe ein anderer Spieler hat, und werde beim Erfüllen dieser Aufgabe erwischt. Ein Misserfolg in dieser Aufgabe ist gegeben, wenn du die Aufgabe des anderen Spielers falsch erraten hast."},
    {points: 1, pack: 1, taskId: 14, 
        description: "Überzeuge einen anderen Spieler, eine deiner anderen Aufgaben zu erfüllen. Bei erfolgreichem Abschluss kann der Spieler eine seiner Aufgaben als erledigt markieren. Du markierst deine zweite Aufgabe nicht als erledigt."},
    {points: 1, pack: 1, taskId: 15, 
        description: "Hilf einem anderen Spieler bei seiner Aufgabe."},
    {points: 1, pack: 1, taskId: 16, 
        description: "Setze einen anderen Spieler in eine unangenehme Lage, indem du vorgibst, ihm bei seiner Aufgabe zu helfen."},
    {points: 1, pack: 1, taskId: 17, 
        description: "Verwende denselben Satz mindestens 4 Mal während eines Abends."},
    {points: 1, pack: 1, taskId: 18, 
        description: "Sprich 15 Minuten lang nur mit 2 Wörtern deiner Wahl."},
    {points: 1, pack: 1, taskId: 19, 
        description: "Erfinde eine einzigartige Geste und verwende sie im Gespräch mit 3 verschiedenen Spielern oder mit einem Spieler 3 Mal."},
    {points: 1, pack: 1, taskId: 20, 
        description: "Ahme 2 Minuten lang die Pose eines anderen Spielers nach. Die Pose sollte charakteristisch sein."},
    {points: 1, pack: 1, taskId: 21, 
        description: "Nimm an einem Dialog teil, in dem du in einem bestimmten Moment mindestens eine Minute lang schweigst."},
    {points: 1, pack: 1, taskId: 22, 
        description: "Verwende im Gespräch unauffällig 3 Zitate aus dem Lieblingsfilm eines der Spieler."},
    {points: 1, pack: 1, taskId: 23, 
        description: "Wähle ein Tier. Verwende im Gespräch 5 Wortspiele, die mit diesem Tier zu tun haben."},
    {points: 1, pack: 1, taskId: 24, 
        description: "Verwende im Gespräch über Filme und Serien unauffällig die Titel von 5 verschiedenen Filmen oder Serien."},
    {points: 1, pack: 1, taskId: 25, 
        description: "Verwende im Gespräch über Musik unauffällig die Titel von 5 Musikgruppen."},
    {points: 1, pack: 1, taskId: 26, 
        description: "Erzähle jemandem einen Witz. Niemand darf lachen."},
    {points: 1, pack: 1, taskId: 27, 
        description: "Sorge dafür, dass ein Spieler einen Prominenten nachahmt, der einem anderen Spieler nicht gefällt."},
    {points: 1, pack: 1, taskId: 28, 
        description: "Wechsle mit einem anderen Spieler ins Flüstern. Der andere Spieler muss ebenfalls ins Flüstern wechseln. Niemand darf euch belauschen."},
    {points: 1, pack: 1, taskId: 29, 
        description: "Lass heimlich drei Personen während ihres Gesprächs die Plätze wechseln."},
    {points: 1, pack: 1, taskId: 30, 
        description: "Füge deinem Kleiderschrank ein Kleidungsstück wie das eines anderen Spielers hinzu. Dieser Spieler muss es bemerken."},
    {points: 1, pack: 1, taskId: 31, 
        description: "Wechsle ein großes oder 3 kleine Kleidungsstücke. Niemand darf dies innerhalb einer Stunde bemerken."},
    {points: 1, pack: 1, taskId: 32, 
        description: "Schlage einem anderen Spieler vor, Kleidungsstücke zu tauschen. Ihr gewinnt, wenn dies innerhalb einer Stunde niemand bemerkt. Der andere Spieler kann in diesem Fall eine seiner Aufgaben als erledigt markieren."},
    {points: 1, pack: 1, taskId: 33, 
        description: "Lerne einen magischen Trick und zeige ihn, oder überzeuge einen anderen Spieler, einen Trick vorzuführen."},
    {points: 1, pack: 1, taskId: 34, 
        description: "Ein anderer Spieler muss seinen Bleistift oder seinen Stift verlieren und dann wiederfinden."},
    {points: 1, pack: 1, taskId: 35, 
        description: "Ein anderer Spieler muss eine Karte (oder etwas Ähnliches) in einer seiner Taschen finden."},
    {points: 1, pack: 1, taskId: 36, 
        description: "Ein anderer Spieler muss eine Karte (oder etwas Ähnliches) in seinen Sachen finden."},
    {points: 1, pack: 1, taskId: 37, 
        description: "Schreibe eine Vorhersage über einen Spieler, was er tun oder sagen wird. Die Handlung oder das Wort sollte ungewöhnlich sein. Nach der Vorhersage zeige dem Spieler den Zettel mit der Vorhersage."},
    {points: 1, pack: 1, taskId: 38, 
        description: "Verstecke einen Gegenstand vom Tisch so, dass niemand innerhalb einer Stunde bemerkt, dass er fehlt."},
    {points: 1, pack: 1, taskId: 39, 
        description: "Überzeuge jemanden, das Hauptthema aus seiner Lieblingsserie zu singen."},
    {points: 1, pack: 1, taskId: 40, 
        description: "Beginne, etwas so Aufregendes zu singen, dass ein anderer Spieler mit einstimmt."},
    {points: 1, pack: 1, taskId: 41, 
        description: "Sing ein Lied falsch, so dass du korrigiert wirst. Oder korrigiere ein Lied, das ein anderer Spieler falsch gesungen hat."},

    {points: 1, pack: 1, taskId: 42, 
        description: "Jemand muss erraten, was du summst. Oder du musst erraten, was ein anderer Spieler summt."},
    {points: 1, pack: 1, taskId: 43, 
        description: "Lass einen anderen Spieler ein Lied deiner Wahl in seine Playlist hinzufügen."},
    {points: 1, pack: 1, taskId: 44, 
        description: "Mache ein schwarzes Zeichen: Schreibe den Namen eines Spielers auf ein Blatt Papier und zeichne eine gruselige Zeichnung. Dieser Spieler muss das schwarze Zeichen finden. Wenn ein anderer Spieler das schwarze Zeichen findet, ist die Aufgabe gescheitert."},
    {points: 1, pack: 1, taskId: 45, 
        description: "Verstecke 5 kleine Objekte (Schätze) im Raum. Zeichne eine Schatzkarte und gib sie einem anderen Spieler. Wenn er alles findet, hast du gewonnen, und er kann eine seiner Aufgaben als erledigt markieren. Wenn jemand anderes den Schatz findet, kann er eine seiner Aufgaben als erledigt markieren. Ihr beide habt verloren."},
    {points: 1, pack: 1, taskId: 46, 
        description: "Mache ein Foto von einem anderen Spieler, als ob du durch ein Fernrohr schaust."},
    {points: 1, pack: 1, taskId: 47, 
        description: "Ein anderer Spieler muss mit dir an einem imaginären Duell teilnehmen."},
    {points: 1, pack: 1, taskId: 48, 
        description: "Jemand muss dich Kapitän nennen."},
    {points: 1, pack: 1, taskId: 49, 
        description: "Finde heraus, welchen Cocktail ein anderer Spieler noch nie probiert hat, und überrede ihn, ihn zu probieren. Dieser Cocktail darf dem Spieler nicht schaden und sollte ihm gefallen."},
    {points: 1, pack: 1, taskId: 50, 
        description: "Probiere mit Erlaubnis der anderen Spieler 4 Getränke."},
    {points: 1, pack: 1, taskId: 51, 
        description: "Überrede jemanden, eine einfache Zutat, wie Zitronensaft oder Sirup, zu seinem Getränk hinzuzufügen."},
    {points: 1, pack: 1, taskId: 52, 
        description: "Ein anderer Spieler muss zu einem bestimmten Zeitpunkt mit einem Getränk in der Hand anfangen zu tanzen."},
    {points: 1, pack: 1, taskId: 53, 
        description: "Dein Getränk muss 4 Mal probiert werden. Das Getränk sollte sicher und angenehm im Geschmack sein."},
    {points: 1, pack: 1, taskId: 54, 
        description: "Mache ein Foto davon, wie jemand etwas zeichnet."},
    {points: 1, pack: 1, taskId: 55, 
        description: "Mache ein Foto davon, wie jemand etwas singt."},
    {points: 1, pack: 1, taskId: 56, 
        description: "Mache ein Foto von anderen Spielern (mindestens drei oder allen) durch einen reflektierenden Gegenstand."},
    {points: 1, pack: 1, taskId: 57, 
        description: "Sorge dafür, dass dein Selfie auf den Handys von drei oder allen Spielern erscheint."},
    {points: 1, pack: 1, taskId: 58, 
        description: "Rekreiere ein Kunstwerk aus Alltagsgegenständen und mache ein Foto davon."},
    {points: 1, pack: 1, taskId: 59, 
        description: "Mache ein Foto von einem anderen Spieler, das an ein bekanntes Kunstwerk erinnert."},
    {points: 1, pack: 1, taskId: 60, 
        description: "Mache ein Foto von einer anderen Person, die auf ihrer Liste von Aufgaben steht."},
    {points: 1, pack: 1, taskId: 61, 
        description: "Sitze 2 Minuten im Raum mit ausgeschaltetem Licht. Dies kann kein Badezimmer oder eine Toilette sein."},
    {points: 1, pack: 1, taskId: 62, 
        description: "Verstecke dich in einem Raum, in dem andere Menschen sind. Sei mindestens eine Minute lang nicht entdeckt."},
    {points: 1, pack: 1, taskId: 63, 
        description: "Wähle einen Spieler und verstecke dich vor ihm innerhalb von 30 Sekunden. Wenn er dich innerhalb von 2 Minuten findet, kann er eine seiner Aufgaben als erledigt markieren. Wenn du gefunden wirst, hast du verloren. Andere Spieler dürfen dich bei dieser Aufgabe nicht fangen."},
    {points: 1, pack: 1, taskId: 64, 
        description: "Wähle einen Spieler und bitte ihn, sich innerhalb von 30 Sekunden zu verstecken. Wenn du ihn innerhalb von 2 Minuten nicht finden kannst, hast du verloren. Wenn du gewinnst, kann der andere Spieler eine seiner Aufgaben als erledigt markieren. Andere Spieler dürfen dich bei dieser Aufgabe nicht fangen."},
    {points: 1, pack: 1, taskId: 65, 
        description: "Schlage einem anderen Spieler ein Spiel vor: Du versteckst einen seiner Gegenstände im Raum innerhalb von 20 Sekunden. Wenn er ihn innerhalb von 5 Minuten finden kann, hast du verloren, und er kann eine seiner Aufgaben als erledigt markieren."},
    {points: 1, pack: 1, taskId: 66, 
        description: "Male den Namen eines anderen Spielers auf deinem Körper. Dieser Spieler muss es bemerken."},
    {points: 1, pack: 1, taskId: 67, 
        description: "Male ein Bild auf einem anderen Spieler, das er mindestens 15 Minuten später bemerken wird. Stelle sicher, dass du mit diesem Spieler in einer engen Beziehung stehst, um diese Aufgabe auszuführen."},
    {points: 1, pack: 1, taskId: 68, 
        description: "Überrede einen anderen Spieler, etwas auf dir zu zeichnen oder zu schreiben."},
    {points: 1, pack: 1, taskId: 69, 
        description: "Gib einem anderen Spieler einen ungewöhnlichen Gegenstand, den er mindestens eine Stunde lang behalten muss."},
    {points: 1, pack: 1, taskId: 70, 
        description: "Gib einem anderen Spieler einen Gegenstand und gehe weg. Sorge dafür, dass dieser Spieler dich findet und dir den Gegenstand zurückgibt."},
    {points: 1, pack: 1, taskId: 71, 
        description: "Ein anderer ausgewählter Spieler muss mindestens zwei verschiedene Zeichnungen anfertigen."},
    {points: 1, pack: 1, taskId: 72, 
        description: "Ein anderer Spieler muss eine Karte oder Zeichnung erstellen, die den Standort eines bestimmten Gegenstandes oder Objekts zeigt."},
    {points: 1, pack: 1, taskId: 73, 
        description: "Bitte einen anderen Spieler, dir ein Gericht ohne eine Zutat zuzubereiten, ohne diese Zutat oder den Typ dieser Zutat zu nennen."}
    // PACK 2
];

module.exports = allTasks;